version: "3.8"

secrets:
  netrc:
    file: /Users/${USER}/.netrc # For Mac
    # file: /home/${USER}/.netrc

services:
  federation:
    image: registry.example.com/nearbyone/ewbi-opg-federation-api:neonephos
    build:
      context: ./
      dockerfile: Dockerfile
      secrets:
        - netrc
    env_file:
      - .env
    restart: on-failure
    platform: linux/arm64
    # platform: linux/amd64
    ports:
      - "8080:8080"

  apigen:
    build:
      context: ./
      dockerfile: Dockerfile.apigen
    platform: linux/arm64
    # platform: linux/arm64
    volumes:
      - ./api:/api

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    platform: linux/arm64
    # platform: linux/amd64
    ports:
      - "8082:8080"
    volumes:
      - ./api/federation/FederationApi_v1.3.0.yaml:/usr/share/nginx/html/doc/swagger.yaml
    environment:
      API_URL: doc/swagger.yaml
